controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

get_sous_departements:
    path: /get-sous-departements/{id}
    controller: App\Controller\AjaxController::getSousDepartements
